workflows:
  android-apk:
    name: Android APK Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      java: 17
    scripts:
      - name: Build APK
        script: |
          cd android-app
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android-app/app/build/outputs/apk/debug/app-debug.apk